# client ids for facebook, twitter
# restart app if changes done here.

facebook:
  key: 337007183102290                               # App ID/API Key
  secret: a43c58c5388e38b8628ccbb28fd89bbd           # App secret

twitter:
  key:  	TSBFjkPRmEmRMnjQKf3w                        # Consumer key
  secret:  	M55sG4PNI0We8LJlcFZCs1dx9DtLYn7XG7c4JpFklik  # Consumer secret

